apiVersion: apps/v1
kind: Service
metadata:
 namespace: webapps
 name: mangodb-svc
spec:
 selector:
  app: mangodb
 ports:
  - name: mongodb-svc
    protocol: TCP
    port: 27017
    targetPort: 27017